HOLOIDS = [
    ["UCp6993wxpyDPHUpavwDFqgg", "Tokino Sora"],
    ["UC0TXe_LYZ4scaW2XMyi5_kw", "AZKi"],
    ["UCDqI2jOz0weumE8s7paEk6g", "Roboco"],
    ["UC-hM6YJuNYVAmUWxeIr9FeA", "Sakura Miko"],
    ["UCdn5BQ06XqgXoAxIhbqw5Rg", "Shirakami Fubuki"],
    ["UCQ0UDLQCjY0rmuxCDE38FGg", "Natsuiro Matsuri"],
    ["UCD8HOxPs4Xvsm8H0ZxXGiBw", "Yozora Mel"],
    ["UC1CfXB_kRs3C-zaeTG3oGyg", "Haachama"],
    ["UCFTLzh12_nrtzqBPsTCqenA", "Aki Rosenthal"],
    ["UC1opHUrw8rvnsadT-iGp7Cg", "Minato Aqua"],
    ["UC1suqwovbL1kzsoaZgFZLKg", "Yuzuki Choco"],
    ["UC7fk0CB07ly8oSl0aqKkqFg", "Nakiri Ayame"],
    ["UCXTpFs_3PqI41qX2d9tL2Rw", "Murusaki Shion"],
    ["UCvzGlP9oQwU--Y0r9id_jnA", "Oozora Subaru"],
    ["UCp-5t9SrOQwXMU7iIjQfARg", "Ookami Mio"],
    ["UCvaTdHTWBGv3MKj3KVqJVCw", "Nekomata Okayu"],
    ["UChAnqc_AY5_I3Px5dig3X1Q", "Inugami Korone"],
    ["UCvInZx9h3jC2JzsIzoOebWg", "Shiruanui Flare"],
    ["UCdyqAaZDKHXg4Ahi7VENThQ", "Shirogane Noel"],
    ["UCCzUftO8KOVkV4wQG1vkUvg", "Houshou Marine"],
    ["UC1DCedRgGHBdm81E1llLhOQ", "Usada Pekora"],
    ["UCl_gCybOJRIgOXw6Qb4qJzQ", "Uruha Rushia"],
    ["UC5CwaMl1eIgY8h02uZw7u8A", "Hoshimachi Suisei"],
    ["UCZlDXzGoo7d44bwdNObFacg", "Amane Kanata"],
    ["UCS9uQI-jC3DE0L4IpXyvr6w", "Kiryu Coco"],
    ["UCqm3BQLlJfvkTsX_hvm0UmA", "Tsunomaki Watame"],
    ["UC1uv2Oq6kNxgATlCiez59hw", "Tokoyami Towa"],
    ["UCa9Y57gfeY0Zro_noHRVrnw", "Himemori Luna"],
    ["UCFKOVgVbGmX65RxO3EtH3iw", "Yukihana Lamy"],
    ["UCAWSyEs_Io8MtpY3m-zqILA", "Momosuzu Nene"],
    ["UCUKD-uaobj9jiqB-VXt71mA", "Shishiro Botan"],
    ["UCK9V2B22uJYu3N7eR_BT9QA", "Omaru Polka"],
    ["UCL_qhgtOy0dy1Agp8vkySQg", "Mori Calliope"],
    ["UCHsx4Hqa-1ORjQTh9TYDhww", "Takanashi Kiara"],
    ["UCMwGHR0BTZuLsmjY_NT5Pwg", "Ninomae Ina'nis"],
    ["UCoSrY_IQQVpmIRZ9Xf-y93g", "Gawr Gura"],
    ["UCyl1z3jo3XHR1riLFKG5UAg", "Amelia Watson"],
        ["UCOyYb1c43VlX9rc_lT6NKQw", "Ayunda Risu"],
    ["UCP0BspO_AMEe3aQqqpo89Dg", "Moona Hoshinova"],
    ["UCAoy6rzhSf4ydcYjJw3WoVg", "Iofi Iofifteen"],
        ["UCKeAhJvy8zgXWbh9duVjIaQ", "Aruran"],
    ["UC6t3-_N8A6ME1JShZHHqOMw", "Miyabi"],
    ["UCZgOv3YDEs-ZnZWDYVwJdmA", "Izuru"],
    ["UCEzsociuFqVwgZuMaZqaCsg", "Kira"],
    ["UC9mf_ZVpouoILRY9NUIaK-w", "Rikka"],
    ["UCNVEsYbiZjH5QLmGeSgTSzg", "Leda"],
    ["UCGNI4MENvnsymYjKiZwv9eg", "Temma"],
    ["UCANDOlYTJT7N5jlRC3zfzVA", "Roberu"],
    ["UChSvpZYRPh0FvG4SJGSga3g", "Shien"],
    ["UCwL7dgTxKo8Y4RFIKWaf8gA", "Aragami Oga"],
    ["UC727SQYUvx5pDDGQpTICNWg", "Anya Melfissa"],
    ["UChgTyjG-pdNvxxhdsXfHQ5Q","Pavolia Reine"],
    ["UCYz_5n-uDuChHtLo7My1HnQ", "Kureji Ollie"]
]
HOLOENIDS = [
    ["UCL_qhgtOy0dy1Agp8vkySQg", "Mori Calliope"],
    ["UCHsx4Hqa-1ORjQTh9TYDhww", "Takanashi Kiara"],
    ["UCMwGHR0BTZuLsmjY_NT5Pwg", "Ninomae Ina'nis"],
    ["UCoSrY_IQQVpmIRZ9Xf-y93g", "Gawr Gura"],
    ["UCyl1z3jo3XHR1riLFKG5UAg", "Amelia Watson"]
]
HOLOidIDS = [
    ["UCOyYb1c43VlX9rc_lT6NKQw", "Ayunda Risu"],
    ["UCP0BspO_AMEe3aQqqpo89Dg", "Moona Hoshinova"],
    ["UCAoy6rzhSf4ydcYjJw3WoVg", "Iofi Iofifteen"],
]
HOLOSTARSIDS = [
    ["UCKeAhJvy8zgXWbh9duVjIaQ", "Aruran"],
    ["UC6t3-_N8A6ME1JShZHHqOMw", "Miyabi"],
    ["UCZgOv3YDEs-ZnZWDYVwJdmA", "Izuru"],
    ["UCEzsociuFqVwgZuMaZqaCsg", "Kira"],
    ["UC9mf_ZVpouoILRY9NUIaK-w", "Rikka"],
    ["UCNVEsYbiZjH5QLmGeSgTSzg", "Leda"],
    ["UCGNI4MENvnsymYjKiZwv9eg", "Temma"],
    ["UCANDOlYTJT7N5jlRC3zfzVA", "Roberu"],
    ["UChSvpZYRPh0FvG4SJGSga3g", "Shien"],
    ["UCwL7dgTxKo8Y4RFIKWaf8gA", "Aragami Oga"]
]
NIJISANJI = [
["UCLpYMk5h1bq8_GAFVBgXhPQ","Kasumi Izumo"],
["UCvmppcdYf4HOv-tFQhHHJMA","Moira"],
["UCBi8YaVyZpiKWN3_Z0dCTfQ","Youko Akabane"],
["UCryOPk2GZ1meIDt53tL30Tw","Masaru Suzuki"],
["UCUzJ90o1EjqUbk2pBAy0_aw","Gilzaren Ⅲ"],
["UCspv01oxUFf_MTSipURRhkA","Kanae"],
["UC_GCs6GARLxEHxy1w40d6VQ", "Mugi Ienaga"],
["UCoztvTULBYd3WmStqYeoHcA","Saku Sasaki"],
["UC6oDys1BGgBsIC3WhG1BovQ","Rin Shizuka"],
["UC48jH1ul-6HOrcSSfoR02fQ","Riri Yuhi"],
["UCpnvhOIJ6BN-vPkYU9ls-Eg","Aki Suzuya"],
["UCYKP16oMX9KKPbrNgo_Kgag","Elu"],
[ "UC1zFJrfEKvCixhsjNSb1toQ", "Sister Claire"],
[ "UChUJbHiTVeGrSkTdBzVfNCQ", "Joe Rikiichi"],
[ "UCLO9QDxVL4bnvRRsz6K4bsQ", "Chihiro Yuki"],
[ "UCjlmCrq4TP1I4xguOtJ-31w", "Debidebi Debiru"],
[ "UC53UDnhAAYwvNO7j_2Ju1cQ", "Dola"],
[ "UCbc8fwhdUNlqi-J99ISYu4A", "Belmond Banderas"],
[ "UCXU7YYxy_iQd3ulXyO-zC2w", "Gaku Fushimi"],
[ "UCv1fFr156jc65EMiLbaLImw", "Toya Kenmochi"],
[ "UC3lNFeJiTq6L3UWoz4g1e-A", "Kou Uzuki"],
[ "UCTIE7LM5X15NVugV7Krp9Hw", "Kakeru Yumeoi"],
[ "UCmUjjW5zF1MMOhYUwwwQv9Q", "Ichigo Ushimi"],
[ "UC6TfqY40Xt1Y0J-N18c85qQ", "Momo Azuchi"],
[ "UCoM_XmK45j504hfUWvN06Qg", "Naru Naruse"],
[ "UCBiqkFJljoxAj10SoP2w2Cg", "Tamaki Fumino"],
[ "UCtAvQ5U0aXyKwm2i4GqFgJg", "Air Harusaki"],
[ "UCD-miitqNY3nyukJ4Fnf4_A", "Mito Tsukino"],
[ "UC0g1AE0DOjBYnLhkgoRWN1w", "Himawari Honma"],
[ "UCfQVs_KuXeNAlGa3fb8rlnQ", "Ritsuki Sakura"],
[ "UCtpB6Bvhs1Um93ziEDACQ8g", "Kazaki Morinaka"],
[ "UC_4tXjqecqox5Uc05ncxpxg", "Yuika Shiina"],
[ "UCsg-YqdqQ-KFF0LNk23BY4A", "Kaede Higuchi"],
[ "UCeK9HFcRZoTrvqcUCtccMoQ", "Hajime Shibuya"],
[ "UCo7TRj3cS-f_1D9ZDmuTsjw", "Chima Machita"],
[ "UCvzVB-EYuHFXHZrObB8a_Og", "Rine Yaguruma"],
[ "UCKMYISTJAQ8xTplUPHiABlA", "Kizuku Yashiro"],
[ "UCWz0CSYCxf4MhRKPDm220AQ", "Shoichi Kanda"],
[ "UCPvGypSgfDkVe7JG2KygK7A", "Mikoto Rindou"],
[ "UCt5-0i4AVHXaWJrL8Wql3mw", "Ryushen"],
[ "UCJubINhCcFXlsBwnHp0wl_g", "Keisuke Maimoto"],
[ "UCsFn_ueskBkMCEyzCEqAOvg", "Chaika Hanabatake"],
[ "UCRV9d6YCYIMUszK-83TwxVA", "Kyoko Todoroki"],
[ "UCwokZsOK_uEre70XayaFnzA", "Utako Suzuka"],
[ "UCRWOdwLRsenx2jLaiCAIU4A", "Sayo Amemori"],
[ "UCiSRx1a2k-0tOg-fs6gAolQ", "Hina Asuka"],
[ "UC9EjSJ8pvxtvPdxLOElv73w", "Makaino Ririmu"],
[ "UCV5ZZlLjk5MKGg3L0n0vbzw", "Rion Takamiya"],
[ "UCmeyo5pRj_6PXG-CsGUuWWg", "Shiba Kuroi"],
[ "UCveZ9Ic1VtcXbsyaBgxPMvg", "Meiji Warabeda"],
[ "UCeShTCVgZyq2lsBW9QwIJcw", "Mirei Gundo"],
[ "UCCVwhI5trmaSxfcze_Ovzfw", "Roa Yuzuki"],
[ "UCg63a3lk6PNeWhVvMRM_mrQ", "Haruka Onomachi"],
[ "UCufQu4q65z63IgE4cfKs1BQ", "Tsumugu Kataribe"],
[ "UCHK5wkevfaGrPr7j3g56Jmw", "Miyako Seto"],
[ "UCX7YkU9nEeaoZbkVLVajcMg", "Nijisanji"],
[ "UCwQ9Uv-m8xkE5PzRc7Bqx3Q", "Era Otogibara"],
[ "UCHVXbQzkl3rDfsXWo8xi2qw", "Ange Katrina"],
[ "UCXRlIK3Cw_TJIQC5kSJJQMg", "Toko Inui"],
[ "UCZ1xuCK1kNmn5RzPYIZop3w", "Lize Helesta"],
[ "UC_a1ZYZ8ZTXpjg9xUY9sj8w", "Lulu Suzuhara"],
[ "UCNW1Ex0r6HsWRD4LCtPwvoQ", "Akina Saegusa"],
[ "UC0WwEfE-jOM2rzjpdfhTzZA", "Manami Aizono"],
[ "UCHX7YpFG8rVwhsHCx34xt7w", "Mahiro Yukishiro"],
[ "UCtnO2N4kPTXmyvedjGWdx3Q", "Levi Elipha"],
[ "UCIytNcoz4pWzXfLda0DoULQ", "Ex Albio"],
[ "UCfipDDn7wY-C-SoUChgxCQQ", "Marin Hayama"],
[ "UCUc8GZfFxtmk7ZwSO7ccQ0g", "Nui Sociere"],
[ "UCmovZ2th3Sqpd00F5RdeigQ", "Hayato Kagami"],
[ "UCGYAYLDE7TZiiC8U6teciDQ", "Fuyuki Hakase"],
[ "UCL34fAoFim9oHLbVzMKFavQ", "Rena Yorumi"],
[ "UCdpUojq0KWZCN9bxXnZwz5w", "Ars Almal"],
[ "UCnRQYHTnRLSF0cLJwMnedCg", "Uiha Aiba"],
[ "UCb5JxV6vKlYVknoJB8TnyYg", "Kai Mayuzumi"],
[ "UCIG9rDtgR45VCZmYnd-4DUw", "Ratna Petit"],
[ "UCkIimWZ9gBJRamKF0rmPU8w", "Kokoro Amamiya"],
[ "UCpNH2Zk2gw3JBjWAKSyZcQQ", "Eli Conifer"],
[ "UC2OacIzd2UxGHRGhdHl1Rhw", "Sou Hayase"],
[ "UC8C1LLhBhf_E2IBPLSDJXlQ", "Kana Sukoya"],
[ "UCHBhnG2G-qN0JrrWmMO2FTA", "Shellin Burgundy"],
[ "UCwrjITPwG4q71HzihV2C7Nw", "Fumi"],
[ "UC9V3Y3_uzU5e-usObb6IE1w", "Sara Hoshikawa"],
[ "UCllKI7VjyANuS1RXatizfLQ", "Karuta Yamagami"],
[ "UCl1oLKcAq93p-pwKfDGhiYQ", "Emma August"],
[ "UCb6ObE-XGCctO3WrjRZC-cw", "Luis Cammy"],
[ "UCerkculBD7YLc_vOGrF7tKg", "Mao Matsukai"],
[ "UC6wvdADTJ88OfIbJYIpAaDA", "Minato Fuwa"],
[ "UCuvk5PilcvDECU7dDZhQiEw", "Tomoe Shirayuki"],
[ "UC1QgXt46-GEvtNjEC1paHnw", "Gwelu Os Gar"],
[ "UCfki3lMEF6SGBFiFfo9kvUA", "Mashiro"],
[ "UC-o-E6I3IC2q8sAoAuM6Umg", "Naraka"],
[ "UCRcLAVTbmx2-iNcXSsupdNA", "Natsume Kurusu"],
[ "UCuep1JCrMvSxOGgGhBfJuYw", "Furen E Lustario"],
[ "UCmZ1Rbthn-6Jm_qOGjYsh5A", "Ibrahim"],
[ "UCwcyyxn6h9ex4sMXGtpQE_g", "Melissa Kinrenka"],
[ "UCGw7lrT-rVZCWHfdG9Frcgg", "Tojiro Genzuki"],
[ "UCo2N7C-Z91waaR6lF3LL_jw", "Haru Kaida"],
[ "UCXW4MqCQn-jCaxlX-nn-BYg", "Kei Nagao"],
[ "UC_82HBGtvwN1hcGeOGHzUBQ", "Kirame Sorahoshi"],
[ "UC69URn8iP4u8D_zUp-IJ1sg", "Meiro Kingyozaka"],
[ "UCkngxfPbmGyGl_RIq4FA3MQ", "Chigusa Nishizono"],
[ "UCe_p3YEuYJb8Np0Ip9dk-FQ", "Akane Asahina"],
[ "UCL_O_HXgLJx3Auteer0n0pA", "Sango Suo"],
[ "UCebT4Aq-3XWb5je1S1FvR_A", "Kohaku Todo"],
[ "UCRqBKoKuX30ruKAq05pCeRQ", "Hisui Kitakoji"],
["UCP4nMSTdwU1KqYWu3UH5DHQ", "Pomu Rainpuff"],
["UCIeSUTOTkF9Hs7q3SGcO-Ow", "Elira Pendora"],
["UCu-J8uIXuLZh16gG-cT1naw", "Finana Ryugu"]

]

ALLHOLOIDS = HOLOIDS + HOLOENIDS + HOLOidIDS + HOLOSTARSIDS
